---

- include_vars: flask.yml

- include: common.yml backend=flask


- name: 'Create Flask directory'
  file: path="{{ flask_dir }}" state=directory

- name: 'Copy requirements.txt'
  copy: src=anaconda_flask_requirements.txt dest="{{ flask_dir }}/requirements.txt"

- name: 'Create virtualenv'
  pip: requirements="{{ flask_dir }}/requirements.txt" virtualenv="{{ flask_venv }}"

- name: 'Copy Flask file'
  template: src=flask/anaconda_flask.py.j2 dest="{{ flask_dir }}/anaconda_flask.py" mode=755 force=yes

- name: 'Add Flask daemontools service'
  template: src=../../common/templates/daemontools.j2 dest="{{ daemontools_service_dir }}/flask/run" mode=755 force=yes
  with_items:
    - { service_name: 'Flask', service_command: '. {{ flask_venv }}/bin/activate && python {{ flask_dir }}/anaconda_flask.py' }
