---

- include_vars: main.yml

- name: 'Install packages'
  apt: name={{ item }} state=present
  with_items:
    - nginx
    - python-virtualenv


- name: 'Create daemontools directories'
  file: path="{{ daemontools_service_dir }}/{{ item }}" state=directory
  with_items:
    - flask

# Web servers

- name: 'Save nginx config'
  template: src=nginx/nginx_anaconda.conf.j2 dest="/etc/nginx/nginx_anaconda_{{ item }}.conf" force=yes
  with_sequence: start=0 end={{ backend_count }}

- name: 'Create nginx daemontols directories'
  file: path="{{ daemontools_service_dir }}/nginx_{{ item }}" state=directory
  with_sequence: start=0 end={{ backend_count }}

- name: 'Save nginx daemontools config'
  template: src=nginx/daemontools.nginx.run.j2 dest="{{ daemontools_service_dir }}/nginx_{{ item }}/run" mode=755 force=yes
  with_sequence: start=0 end={{ backend_count }}


# Application servers

# Flask

- include_vars: flask.yml

- name: 'Create Flask directory'
  file: path="{{ flask_dir }}" state=directory

- name: 'Copy requirements.txt'
  copy: src=requirements.txt dest="{{ flask_dir }}/requirements.txt"

- name: 'Create virtualenv'
  pip: requirements="{{ flask_dir }}/requirements.txt" virtualenv="{{ flask_venv }}"

- name: 'Copy Flask file'
  template: src=flask/anaconda_flask.py.j2 dest="{{ flask_dir }}/anaconda_flask.py" mode=755 force=yes

- name: 'Add Flask daemontools service'
  template: src=flask/daemontools.flask.run.j2 dest="{{ daemontools_service_dir }}/flask/run" mode=755 force=yes
