---

- include_vars: main.yml

- name: 'Install packages'
  apt: name="{{ item }}" state=present
  with_items:
    - nginx
    - python-virtualenv

# Web servers

- name: 'Save nginx config'
  template: src=nginx/nginx_anaconda.conf.j2 dest="/etc/nginx/nginx_{{ item.1 }}.conf" force=yes
  with_indexed_items: "{{ backends }}"


# This is some bullshit where I can't use with_items
# on an include until ansible 2.
- include: flask.yml
- include: nodejs.yml
