---

- include_vars: main.yml

- name: 'Install packages'
  apt: name={{ item }} state=present
  with_items:
    - nginx
    - python-virtualenv


- name: 'Create daemontools directories'
  file: path="{{ daemontools_service_dir }}/{{ item }}" state=directory
  with_items:
    - flask
    - nginx_flask

# Web servers

- name: 'Save nginx config'
  template: src=nginx/nginx_anaconda.conf.j2 dest="/etc/nginx/nginx_{{ item }}.conf" force=yes
  with_items: "{{ backends }}"


# This is a pain to use templates with so for now just do each backend and later
# on figure out a way to template them.

- name: 'Save flask nginx daemontools config'
  template: src=../../common/templates/daemontools.j2 dest="{{ daemontools_service_dir }}/nginx_flask/run" mode=755 force=yes
  with_items:
    - { service_name: 'nginx', service_command: '/usr/sbin/nginx -c /etc/nginx/nginx_flask.conf'}


# Application servers

# Flask

- include_vars: flask.yml

- name: 'Create Flask directory'
  file: path="{{ flask_dir }}" state=directory

- name: 'Copy requirements.txt'
  copy: src=requirements.txt dest="{{ flask_dir }}/requirements.txt"

- name: 'Create virtualenv'
  pip: requirements="{{ flask_dir }}/requirements.txt" virtualenv="{{ flask_venv }}"

- name: 'Copy Flask file'
  template: src=flask/anaconda_flask.py.j2 dest="{{ flask_dir }}/anaconda_flask.py" mode=755 force=yes

- name: 'Add Flask daemontools service'
  template: src=../../common/templates/daemontools.j2 dest="{{ daemontools_service_dir }}/flask/run" mode=755 force=yes
  with_items:
    - { service_name: 'Flask', service_command: '. {{ flask_venv }}/bin/activate && python {{ flask_dir }}/anaconda_flask.py' }
