---

- include_vars: nodejs.yml

- include: common.yml backend=nodejs



- name: 'Add nodejs key to keyring'
  apt_key: url="https://deb.nodesource.com/gpgkey/nodesource.gpg.key" state=present

- name: 'Add nodejs apt repo'
  apt_repository: repo="deb https://deb.nodesource.com/node_5.x {{ ansible_distribution_release }} main" state=present

- name: 'Install nodejs'
  apt: name=nodejs state=latest update_cache=yes



- name: 'Create nodejs directory'
  file: path="{{ nodejs_dir }}" state=directory

- name: "Copy nodejs file"
  template: src=nodejs/anaconda_nodejs.js.j2 dest="{{ nodejs_dir }}/anaconda_nodejs.js"

- name: 'Add nodejs daemontools service'
  template: src=../../common/templates/daemontools.j2 dest="{{ daemontools_service_dir }}/nodejs/run" mode=755 force=yes
  with_items:
    - { service_name: 'nodejs', service_command: 'nodejs {{ nodejs_dir }}/anaconda_nodejs.js' }
