---

- name: 'Install haproxy'
  apt: name=haproxy state=present

- name: 'Save haproxy config file'
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

# Daemontools stuff

- name: 'Create haproxy daemontols directory'
  file: path=/etc/service/haproxy state=directory

- name: 'Save haproxy daemontools config'
  template: src=../../common/templates/daemontools.j2 dest=/etc/service/haproxy/run mode=755
  with_items:
    - { service_name: 'Haproxy', service_command: '/usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg' }
